### ISSUE TITLE
RabbitMQ kept open after github actions

### ISSUE THREAD

**Issue by evilmonkey19** [Namoshek/rabbitmq-github-action#3]
Hi! 

Thank you very much for such a wonderful action. I currently using it in a project in order to do the automatic testing whenever I do a push. If I try to run the github action using act in WSL2 in Windows 11 using the command `act -P ubuntu-latest=-self-hosted` the containers keeps running afterwards. It isn't a problem for github, but it can be if you run it locally.

I would suggest to close the container afterwards. As well I think it would be a good idea to change the name of the container to something random as in github actions it just runs for a few minutes, a finite lifecycle.

Thanks for this awesome project!

**Comment by Namoshek** [comment]
Can you maybe add a simple script to shut down the container at the bottom of your build?
```yaml
jobs:
  build:
    steps:
      - ...

      - name: Start RabbitMQ
        uses: namoshek/rabbitmq-github-action@v1
        with:
          ...
          container-name: 'mqtt'

      - ...
  
      - run: docker stop mqtt
```
If you've an idea how to add a shutdown step implicitly, I'm open to contributions!
